Test/mejora coverage (#11)
* tests: Ajsutes y mejoras archivos de pruebas de endpoints.

* k8s: Remuevo atributo verison porque kuvbernetes la deprecio y lanza alerta.

* k8s: Cambio de host de nombre a DNS.

* k8s: nombre persionalizado al puerto de la BD para no confundir con el numero concreto de puerto.

* feat: Agrego reglas de negocio, seguridad en manejo de la clave e integracion con BD.

* feat: Agrego ping a BD en la ruta del home.

* feat: Integracion de logueo con datos de la BD.

* BD: Inicio de la BD en tiempo de inicio y escalamiento de  la app.

* dependencies: Agrego dependencias necesarias para integrar la app con la BD de posgresql.

* feat: Entidad User necesaria para regisrar usuarios en BD.

* BD: Archivos de configuracion e integracion con BD

* cors: Agrego dependencia para soportar cors a la web.

* test: mejoramiento unit test y coverage.

* refactor: Mejoras de mantenibilidad y testabilidad. Ajuste en pipeline.

* fix ci

* fix ci

* fix ci

* fix variables de ambiente para BD. estaba mal.

---------

Co-authored-by: Jhon Freddy Puentes Nuñez <jhonfredypuentesnunez@192.168.10.9>

diff --git a/.github/workflows/ci_pipeline.yml b/.github/workflows/ci_pipeline.yml
--- a/.github/workflows/ci_pipeline.yml
+++ b/.github/workflows/ci_pipeline.yml
@@ -302,21 +302,25 @@ jobs:
         python-version: [3.10]
     steps:
       - uses: actions/checkout@v2
-      - name: Install pipenv
-        working-directory: ./backend/seguridad_servicio/gestor_usuarios
-        run: pip install pipenv
-      - name: Install dependencies
-        working-directory: ./backend/seguridad_servicio/gestor_usuarios
-        run: pip install -r requirements.txt
-      - name: Set PYTHONPATH
-        run: echo "PYTHONPATH=$PWD/backend/seedwork_compartido:$PWD/backend/seguridad_servicio/gestor_usuarios" >> $GITHUB_ENV
-      - name: Print PYTHONPATH
-        run: echo $PYTHONPATH
-      - name: Run unit tests
-        working-directory: ./backend
-        env:
-          PYTHONPATH: ${{ env.PYTHONPATH }}
-        run: coverage run --omit="*/tests/*,*/__init__.py" -m unittest discover -s seguridad_servicio/gestor_usuarios/tests
-      - name: Run coverage report
-        working-directory: ./backend
-        run: coverage report --fail-under=70
+
+      - name: Create virtual environment
+        working-directory: ./backend/seguridad_servicio
+        run: python3 -m venv venv
+
+      - name: Activate virtual environment and install dependencies
+        working-directory: ./backend/seguridad_servicio
+        run: |
+          source venv/bin/activate
+          pip install -r requirements-test-gestor-usuarios.txt
+
+      - name: Run unit tests with coverage
+        working-directory: ./backend/seguridad_servicio
+        run: |
+          source venv/bin/activate
+          coverage run --source=gestor_usuarios -m pytest
+          coverage report -m
+          coverage_percentage=$(coverage report | grep TOTAL | awk '{print $4}' | sed 's/%//')
+          if (( $(echo "$coverage_percentage < 70" | bc -l) )); then
+            echo "ERROR: La cobertura de pruebas es menor al 70% ($coverage_percentage%)"
+            exit 1
+          fi
